### ISSUE TITLE
fails to build on Fedora25 against 4.11.10-200.fc25.x86_64

### ISSUE THREAD

**Issue by netllama** [michaelgugino/rtl8188EUS#1]
Attempting to build on a Fedora25 system running 4.11.10-200.fc25.x86_64 fails:
```
$ make -j4
"******************************************"
"NO SKRC,we will use default KSRC"
"******************************************"
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/4.11.10-200.fc25.x86_64/build M=/home/netllama/stuff/rtl8188EUS  modules
make[1]: Entering directory '/usr/src/kernels/4.11.10-200.fc25.x86_64'
"******************************************"
"NO SKRC,we will use default KSRC"
"******************************************"
  CC [M]  /home/netllama/stuff/rtl8188EUS/core/rtw_cmd.o
  CC [M]  /home/netllama/stuff/rtl8188EUS/core/rtw_security.o
  CC [M]  /home/netllama/stuff/rtl8188EUS/core/rtw_debug.o
  CC [M]  /home/netllama/stuff/rtl8188EUS/core/rtw_io.o
In file included from /home/netllama/stuff/rtl8188EUS/include/drv_types.h:32:0,
                 from /home/netllama/stuff/rtl8188EUS/core/rtw_io.c:52:
/home/netllama/stuff/rtl8188EUS/include/osdep_service.h: In function ‘thread_enter’:
/home/netllama/stuff/rtl8188EUS/include/osdep_service.h:342:2: error: implicit declaration of function ‘allow_signal’ [-Werror=implicit-function-declaration]
  allow_signal(SIGTERM);
  ^~~~~~~~~~~~
/home/netllama/stuff/rtl8188EUS/include/osdep_service.h: In function ‘flush_signals_thread’:
/home/netllama/stuff/rtl8188EUS/include/osdep_service.h:352:6: error: implicit declaration of function ‘signal_pending’ [-Werror=implicit-function-declaration]
  if (signal_pending (current))
      ^~~~~~~~~~~~~~
/home/netllama/stuff/rtl8188EUS/include/osdep_service.h:354:3: error: implicit declaration of function ‘flush_signals’ [-Werror=implicit-function-declaration]
   flush_signals(current);
   ^~~~~~~~~~~~~
cc1: some warnings being treated as errors
scripts/Makefile.build:294: recipe for target '/home/netllama/stuff/rtl8188EUS/core/rtw_io.o' failed
make[2]: *** [/home/netllama/stuff/rtl8188EUS/core/rtw_io.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /home/netllama/stuff/rtl8188EUS/include/drv_types.h:32:0,
                 from /home/netllama/stuff/rtl8188EUS/core/rtw_debug.c:22:
/home/netllama/stuff/rtl8188EUS/include/osdep_service.h: In function ‘thread_enter’:
/home/netllama/stuff/rtl8188EUS/include/osdep_service.h:342:2: error: implicit declaration of function ‘allow_signal’ [-Werror=implicit-function-declaration]
  allow_signal(SIGTERM);
  ^~~~~~~~~~~~
/home/netllama/stuff/rtl8188EUS/include/osdep_service.h: In function ‘flush_signals_thread’:
/home/netllama/stuff/rtl8188EUS/include/osdep_service.h:352:6: error: implicit declaration of function ‘signal_pending’ [-Werror=implicit-function-declaration]
  if (signal_pending (current))
      ^~~~~~~~~~~~~~
/home/netllama/stuff/rtl8188EUS/include/osdep_service.h:354:3: error: implicit declaration of function ‘flush_signals’ [-Werror=implicit-function-declaration]
   flush_signals(current);
   ^~~~~~~~~~~~~
cc1: some warnings being treated as errors
scripts/Makefile.build:294: recipe for target '/home/netllama/stuff/rtl8188EUS/core/rtw_debug.o' failed
make[2]: *** [/home/netllama/stuff/rtl8188EUS/core/rtw_debug.o] Error 1
In file included from /home/netllama/stuff/rtl8188EUS/include/drv_types.h:32:0,
                 from /home/netllama/stuff/rtl8188EUS/core/rtw_security.c:22:
/home/netllama/stuff/rtl8188EUS/include/osdep_service.h: In function ‘thread_enter’:
/home/netllama/stuff/rtl8188EUS/include/osdep_service.h:342:2: error: implicit declaration of function ‘allow_signal’ [-Werror=implicit-function-declaration]
  allow_signal(SIGTERM);
  ^~~~~~~~~~~~
/home/netllama/stuff/rtl8188EUS/include/osdep_service.h: In function ‘flush_signals_thread’:
/home/netllama/stuff/rtl8188EUS/include/osdep_service.h:352:6: error: implicit declaration of function ‘signal_pending’ [-Werror=implicit-function-declaration]
  if (signal_pending (current))
      ^~~~~~~~~~~~~~
/home/netllama/stuff/rtl8188EUS/include/osdep_service.h:354:3: error: implicit declaration of function ‘flush_signals’ [-Werror=implicit-function-declaration]
   flush_signals(current);
   ^~~~~~~~~~~~~
/home/netllama/stuff/rtl8188EUS/core/rtw_security.c: In function ‘aes_cipher’:
/home/netllama/stuff/rtl8188EUS/core/rtw_security.c:1598:5: warning: this ‘for’ clause does not guard... [-Wmisleading-indentation]
     for (j = 0; j < 8; j++)
     ^~~
/home/netllama/stuff/rtl8188EUS/core/rtw_security.c:1601:2: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘for’
  payload_index = hdrlen + 8;
  ^~~~~~~~~~~~~
/home/netllama/stuff/rtl8188EUS/core/rtw_security.c: In function ‘aes_decipher’:
/home/netllama/stuff/rtl8188EUS/core/rtw_security.c:1983:5: warning: this ‘for’ clause does not guard... [-Wmisleading-indentation]
     for (j = 0; j < 8; j++)
     ^~~
/home/netllama/stuff/rtl8188EUS/core/rtw_security.c:1986:2: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘for’
  payload_index = hdrlen + 8;
  ^~~~~~~~~~~~~
cc1: some warnings being treated as errors
scripts/Makefile.build:294: recipe for target '/home/netllama/stuff/rtl8188EUS/core/rtw_security.o' failed
make[2]: *** [/home/netllama/stuff/rtl8188EUS/core/rtw_security.o] Error 1
In file included from /home/netllama/stuff/rtl8188EUS/include/drv_types.h:32:0,
                 from /home/netllama/stuff/rtl8188EUS/core/rtw_cmd.c:22:
/home/netllama/stuff/rtl8188EUS/include/osdep_service.h: In function ‘thread_enter’:
/home/netllama/stuff/rtl8188EUS/include/osdep_service.h:342:2: error: implicit declaration of function ‘allow_signal’ [-Werror=implicit-function-declaration]
  allow_signal(SIGTERM);
  ^~~~~~~~~~~~
/home/netllama/stuff/rtl8188EUS/include/osdep_service.h: In function ‘flush_signals_thread’:
/home/netllama/stuff/rtl8188EUS/include/osdep_service.h:352:6: error: implicit declaration of function ‘signal_pending’ [-Werror=implicit-function-declaration]
  if (signal_pending (current))
      ^~~~~~~~~~~~~~
/home/netllama/stuff/rtl8188EUS/include/osdep_service.h:354:3: error: implicit declaration of function ‘flush_signals’ [-Werror=implicit-function-declaration]
   flush_signals(current);
   ^~~~~~~~~~~~~
cc1: some warnings being treated as errors
scripts/Makefile.build:294: recipe for target '/home/netllama/stuff/rtl8188EUS/core/rtw_cmd.o' failed
make[2]: *** [/home/netllama/stuff/rtl8188EUS/core/rtw_cmd.o] Error 1
Makefile:1496: recipe for target '_module_/home/netllama/stuff/rtl8188EUS' failed
make[1]: *** [_module_/home/netllama/stuff/rtl8188EUS] Error 2
make[1]: Leaving directory '/usr/src/kernels/4.11.10-200.fc25.x86_64'
Makefile:1367: recipe for target 'modules' failed
make: *** [modules] Error 2
```

**Comment by michaelgugino** [comment]
Hi.  I haven't tried with Fedora 25; the branch for fedora 26 may work, I'm not sure.  In any case, you should probably use this driver:  https://github.com/lwfinger/rtl8188eu

This is a more concrete effort for cleaning up the driver code than I have implemented.  I recommend installing with dkms, it works well for me.

**Comment by netllama** [comment]
Unfortunately, the lwfinger/rtl8188eu driver doesn't work with NetworkManager at all, and the author has made it very clear that he has no intention of fixing it.

**Comment by michaelgugino** [comment]
I'm not sure what you mean.  I have used lwfinger's driver with Fedora 26, using the default gnome desktop.  In any case, lwfinger's driver is a cleaned-up version of the vendor's driver.  The code here is a less-well cleaned up version of the vendor's driver.
